begin;

create extension if not exists pgcrypto with schema extensions;

create type public.sex_type as enum ('female', 'male', 'intersex', 'prefer_not_to_say');
create type public.account_status as enum ('pending', 'active', 'inactive', 'suspended');
create type public.hospital_operating_status as enum ('open', 'limited', 'temporarily_closed', 'closed');
create type public.verification_status as enum ('pending', 'verified', 'rejected');
create type public.availability_status as enum ('available', 'limited', 'unavailable');
create type public.emergency_room_state as enum ('available', 'limited', 'full', 'temporarily_closed');
create type public.consultation_type as enum ('face_to_face', 'online', 'emergency', 'guest_online');
create type public.consultation_status as enum ('pending', 'approved', 'rejected', 'scheduled', 'in_progress', 'completed', 'cancelled');
create type public.guest_request_status as enum (
  'pending_verification',
  'otp_verified',
  'pending_doctor_review',
  'approved',
  'rejected',
  'temporary_patient_created',
  'account_activation_pending',
  'consultation_scheduled',
  'consultation_completed',
  'cancelled'
);
create type public.urgency_level as enum ('self_care', 'routine', 'urgent', 'emergency');
create type public.medical_result_status as enum (
  'uploaded',
  'ocr_processing',
  'ai_analysis_pending',
  'pending_doctor_review',
  'doctor_confirmed',
  'doctor_modified',
  'rejected',
  'saved_to_patient_record'
);
create type public.conversation_status as enum ('pending', 'active', 'closed', 'archived');

create table public.roles (
  id smallint generated by default as identity primary key,
  role_name text not null unique check (role_name in ('guest', 'patient', 'doctor', 'hospital_admin', 'super_admin')),
  description text not null,
  created_at timestamptz not null default now()
);

insert into public.roles (role_name, description) values
  ('guest', 'Verified visitor without an official patient account'),
  ('patient', 'Patient with access to their own care records'),
  ('doctor', 'Licensed clinician assigned by a hospital administrator'),
  ('hospital_admin', 'Administrator restricted to one assigned hospital'),
  ('super_admin', 'Platform administrator for CareNavigator PH');

create table public.hospital_classifications (
  id uuid primary key default gen_random_uuid(),
  classification_name text not null unique,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.hospital_classifications (classification_name, description) values
  ('Primary Hospital', 'First-contact and basic inpatient care'),
  ('Secondary Hospital', 'Specialist services and intermediate-level hospital care'),
  ('Tertiary Hospital', 'Advanced specialist, intensive, and referral care'),
  ('Specialty Hospital', 'Focused care for a particular condition or patient group');

create table public.hospitals (
  id uuid primary key default gen_random_uuid(),
  hospital_name text not null,
  classification_id uuid references public.hospital_classifications(id) on delete set null,
  address text not null,
  city text,
  province text,
  latitude numeric(9, 6) check (latitude between -90 and 90),
  longitude numeric(9, 6) check (longitude between -180 and 180),
  contact_number text,
  emergency_contact_number text,
  email text,
  description text not null default '',
  operating_hours jsonb not null default '{}'::jsonb,
  operating_status public.hospital_operating_status not null default 'open',
  verification_status public.verification_status not null default 'pending',
  image_url text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_name, address)
);

create table public.users (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  role_id smallint not null references public.roles(id),
  first_name text not null default '',
  middle_name text,
  last_name text not null default '',
  email text,
  mobile_number text,
  birth_date date,
  sex public.sex_type,
  address text,
  hospital_id uuid references public.hospitals(id) on delete set null,
  account_status public.account_status not null default 'pending',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.hospital_departments (
  id uuid primary key default gen_random_uuid(),
  hospital_id uuid not null references public.hospitals(id) on delete cascade,
  department_name text not null,
  description text not null default '',
  availability_status public.availability_status not null default 'available',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_id, department_name)
);

create table public.hospital_services (
  id uuid primary key default gen_random_uuid(),
  hospital_id uuid not null references public.hospitals(id) on delete cascade,
  department_id uuid references public.hospital_departments(id) on delete set null,
  service_name text not null,
  description text not null default '',
  availability_status public.availability_status not null default 'available',
  operating_hours jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (hospital_id, service_name)
);

create table public.hospital_rooms (
  id uuid primary key default gen_random_uuid(),
  hospital_id uuid not null references public.hospitals(id) on delete cascade,
  room_type text not null,
  total_rooms integer not null default 0 check (total_rooms >= 0),
  available_rooms integer not null default 0 check (available_rooms >= 0),
  occupied_rooms integer not null default 0 check (occupied_rooms >= 0),
  status public.availability_status not null default 'available',
  last_updated timestamptz not null default now(),
  check (available_rooms + occupied_rooms <= total_rooms),
  unique (hospital_id, room_type)
);

create table public.hospital_beds (
  id uuid primary key default gen_random_uuid(),
  hospital_id uuid not null references public.hospitals(id) on delete cascade,
  department_id uuid references public.hospital_departments(id) on delete set null,
  bed_type text not null default 'regular',
  total_beds integer not null default 0 check (total_beds >= 0),
  available_beds integer not null default 0 check (available_beds >= 0),
  occupied_beds integer not null default 0 check (occupied_beds >= 0),
  last_updated timestamptz not null default now(),
  check (available_beds + occupied_beds <= total_beds),
  unique (hospital_id, department_id, bed_type)
);

create table public.emergency_room_status (
  id uuid primary key default gen_random_uuid(),
  hospital_id uuid not null unique references public.hospitals(id) on delete cascade,
  status public.emergency_room_state not null default 'available',
  available_beds integer not null default 0 check (available_beds >= 0),
  current_patient_count integer not null default 0 check (current_patient_count >= 0),
  maximum_capacity integer not null default 0 check (maximum_capacity >= 0),
  last_updated timestamptz not null default now(),
  check (current_patient_count <= maximum_capacity or maximum_capacity = 0)
);

create table public.hospital_facility_status (
  id uuid primary key default gen_random_uuid(),
  hospital_id uuid not null references public.hospitals(id) on delete cascade,
  facility_type text not null check (facility_type in ('icu', 'operating_room', 'ambulance', 'laboratory', 'pharmacy')),
  status public.availability_status not null default 'available',
  available_units integer check (available_units is null or available_units >= 0),
  notes text,
  last_updated timestamptz not null default now(),
  unique (hospital_id, facility_type)
);

create table public.doctors (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.users(id) on delete cascade,
  hospital_id uuid not null references public.hospitals(id) on delete restrict,
  department_id uuid references public.hospital_departments(id) on delete set null,
  display_name text not null,
  specialization text not null,
  license_number text not null unique,
  availability_status public.availability_status not null default 'available',
  consultation_fee numeric(10, 2) check (consultation_fee is null or consultation_fee >= 0),
  biography text,
  created_by_admin uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.doctor_schedules (
  id uuid primary key default gen_random_uuid(),
  doctor_id uuid not null references public.doctors(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  starts_at time not null,
  ends_at time not null,
  consultation_type public.consultation_type not null default 'online',
  slot_minutes integer not null default 30 check (slot_minutes between 10 and 240),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  check (ends_at > starts_at),
  unique (doctor_id, day_of_week, starts_at, consultation_type)
);

create table public.patients (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references public.users(id) on delete cascade,
  patient_number text unique,
  created_by_doctor uuid references public.doctors(id) on delete set null,
  guest_request_id uuid,
  primary_hospital_id uuid references public.hospitals(id) on delete set null,
  blood_type text check (blood_type is null or blood_type in ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
  emergency_contact jsonb not null default '{}'::jsonb,
  allergies text[] not null default '{}',
  existing_conditions text[] not null default '{}',
  identity_verification_status public.verification_status not null default 'pending',
  account_activation_status public.account_status not null default 'pending',
  converted_from_guest boolean not null default false,
  converted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.doctor_patient_assignments (
  id uuid primary key default gen_random_uuid(),
  doctor_id uuid not null references public.doctors(id) on delete cascade,
  patient_id uuid not null references public.patients(id) on delete cascade,
  assigned_at timestamptz not null default now(),
  ended_at timestamptz,
  notes text,
  unique (doctor_id, patient_id, assigned_at),
  check (ended_at is null or ended_at >= assigned_at)
);

create sequence public.guest_consultation_reference_seq;

create table public.guest_consultation_requests (
  id uuid primary key default gen_random_uuid(),
  submitted_by uuid references auth.users(id) on delete set null,
  reference_number text not null unique,
  full_name text not null,
  birth_date date not null,
  sex public.sex_type not null,
  mobile_number text not null,
  email text,
  address text not null,
  latitude numeric(9, 6) check (latitude between -90 and 90),
  longitude numeric(9, 6) check (longitude between -180 and 180),
  symptoms text not null,
  symptom_duration text not null,
  consultation_reason text not null,
  existing_conditions text[] not null default '{}',
  allergies text[] not null default '{}',
  current_medications text[] not null default '{}',
  urgency_level public.urgency_level,
  preferred_hospital_id uuid references public.hospitals(id) on delete set null,
  preferred_department_id uuid references public.hospital_departments(id) on delete set null,
  assigned_doctor_id uuid references public.doctors(id) on delete set null,
  preferred_schedule timestamptz,
  identification_file_path text,
  otp_verification_status public.verification_status not null default 'verified',
  request_status public.guest_request_status not null default 'otp_verified',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.patients
  add constraint patients_guest_request_id_fkey
  foreign key (guest_request_id) references public.guest_consultation_requests(id) on delete set null;

create table public.consultations (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid references public.patients(id) on delete restrict,
  guest_request_id uuid references public.guest_consultation_requests(id) on delete restrict,
  doctor_id uuid not null references public.doctors(id) on delete restrict,
  hospital_id uuid not null references public.hospitals(id) on delete restrict,
  consultation_type public.consultation_type not null,
  appointment_date timestamptz not null,
  status public.consultation_status not null default 'pending',
  chief_complaint text not null,
  doctor_notes text,
  confirmed_diagnosis text,
  treatment_plan text,
  meeting_link text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (num_nonnulls(patient_id, guest_request_id) = 1)
);

create table public.medical_records (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.patients(id) on delete restrict,
  doctor_id uuid not null references public.doctors(id) on delete restrict,
  hospital_id uuid not null references public.hospitals(id) on delete restrict,
  consultation_id uuid references public.consultations(id) on delete set null,
  record_type text not null,
  title text not null,
  description text,
  confirmed_diagnosis text,
  treatment_plan text,
  record_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.laboratory_results (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.patients(id) on delete restrict,
  doctor_id uuid not null references public.doctors(id) on delete restrict,
  hospital_id uuid not null references public.hospitals(id) on delete restrict,
  consultation_id uuid references public.consultations(id) on delete set null,
  test_name text not null,
  extracted_text text,
  ai_summary text,
  ai_possible_findings jsonb,
  doctor_confirmed_findings text,
  professional_interpretation text,
  file_path text not null,
  verification_status public.medical_result_status not null default 'uploaded',
  confirmed_at timestamptz,
  uploaded_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.prescriptions (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.patients(id) on delete restrict,
  doctor_id uuid not null references public.doctors(id) on delete restrict,
  consultation_id uuid not null references public.consultations(id) on delete restrict,
  medication_name text not null,
  dosage text not null,
  frequency text not null,
  duration text not null,
  instructions text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ai_assessments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  patient_id uuid references public.patients(id) on delete cascade,
  guest_request_id uuid references public.guest_consultation_requests(id) on delete cascade,
  symptoms text not null,
  symptom_duration text,
  possible_conditions jsonb not null default '[]'::jsonb,
  urgency_level public.urgency_level not null,
  warning_signs jsonb not null default '[]'::jsonb,
  recommended_action text not null,
  recommended_department text,
  recommended_hospital_id uuid references public.hospitals(id) on delete set null,
  groq_response jsonb not null default '{}'::jsonb,
  disclaimer text not null default 'This preliminary guidance is not a diagnosis. Consult a licensed healthcare professional.',
  model_name text,
  created_at timestamptz not null default now(),
  check (num_nonnulls(user_id, patient_id, guest_request_id) >= 1)
);

create table public.chat_conversations (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid references public.patients(id) on delete cascade,
  guest_request_id uuid references public.guest_consultation_requests(id) on delete cascade,
  doctor_id uuid not null references public.doctors(id) on delete cascade,
  consultation_id uuid not null unique references public.consultations(id) on delete cascade,
  status public.conversation_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (num_nonnulls(patient_id, guest_request_id) = 1)
);

create table public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.chat_conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete restrict,
  message text,
  attachment_path text,
  sent_at timestamptz not null default now(),
  delivered_at timestamptz,
  read_at timestamptz,
  check (message is not null or attachment_path is not null)
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  guest_request_id uuid references public.guest_consultation_requests(id) on delete cascade,
  title text not null,
  message text not null,
  notification_type text not null,
  reference_id uuid,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  check (num_nonnulls(user_id, guest_request_id) >= 1)
);

create table public.hospital_announcements (
  id uuid primary key default gen_random_uuid(),
  hospital_id uuid references public.hospitals(id) on delete cascade,
  title text not null,
  message text not null,
  is_global boolean not null default false,
  published_at timestamptz not null default now(),
  expires_at timestamptz,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  check ((is_global and hospital_id is null) or (not is_global and hospital_id is not null)),
  check (expires_at is null or expires_at > published_at)
);

create table public.audit_logs (
  id bigint generated always as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  hospital_id uuid references public.hospitals(id) on delete set null,
  action text not null,
  module text not null,
  record_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  ip_address inet,
  created_at timestamptz not null default now()
);

create index hospitals_public_directory_idx on public.hospitals (verification_status, operating_status, province, city);
create index hospitals_classification_idx on public.hospitals (classification_id);
create index users_role_idx on public.users (role_id);
create index users_hospital_idx on public.users (hospital_id) where hospital_id is not null;
create index departments_hospital_idx on public.hospital_departments (hospital_id, availability_status);
create index services_hospital_idx on public.hospital_services (hospital_id, availability_status);
create index services_department_idx on public.hospital_services (department_id) where department_id is not null;
create index rooms_hospital_idx on public.hospital_rooms (hospital_id, status);
create index beds_hospital_idx on public.hospital_beds (hospital_id);
create index beds_department_idx on public.hospital_beds (department_id) where department_id is not null;
create index facility_status_hospital_idx on public.hospital_facility_status (hospital_id, facility_type);
create index doctors_hospital_status_idx on public.doctors (hospital_id, availability_status);
create index doctors_department_idx on public.doctors (department_id) where department_id is not null;
create index doctor_schedules_lookup_idx on public.doctor_schedules (doctor_id, day_of_week, is_active);
create index patients_primary_hospital_idx on public.patients (primary_hospital_id);
create index patients_created_by_idx on public.patients (created_by_doctor) where created_by_doctor is not null;
create unique index doctor_patient_active_unique_idx on public.doctor_patient_assignments (doctor_id, patient_id) where ended_at is null;
create index assignments_patient_active_idx on public.doctor_patient_assignments (patient_id, doctor_id) where ended_at is null;
create index guest_requests_submitter_idx on public.guest_consultation_requests (submitted_by, created_at desc);
create index guest_requests_review_idx on public.guest_consultation_requests (preferred_hospital_id, request_status, created_at);
create index guest_requests_doctor_idx on public.guest_consultation_requests (assigned_doctor_id, request_status) where assigned_doctor_id is not null;
create index consultations_patient_idx on public.consultations (patient_id, appointment_date desc) where patient_id is not null;
create index consultations_doctor_idx on public.consultations (doctor_id, appointment_date desc);
create index consultations_hospital_status_idx on public.consultations (hospital_id, status, appointment_date);
create index medical_records_patient_date_idx on public.medical_records (patient_id, record_date desc);
create index medical_records_consultation_idx on public.medical_records (consultation_id) where consultation_id is not null;
create index laboratory_results_patient_idx on public.laboratory_results (patient_id, uploaded_at desc);
create index laboratory_results_status_idx on public.laboratory_results (doctor_id, verification_status, uploaded_at);
create index prescriptions_patient_idx on public.prescriptions (patient_id, created_at desc);
create index prescriptions_consultation_idx on public.prescriptions (consultation_id);
create index ai_assessments_user_idx on public.ai_assessments (user_id, created_at desc) where user_id is not null;
create index ai_assessments_patient_idx on public.ai_assessments (patient_id, created_at desc) where patient_id is not null;
create index chat_messages_conversation_idx on public.chat_messages (conversation_id, sent_at);
create index notifications_unread_idx on public.notifications (user_id, created_at desc) where not is_read;
create index announcements_active_idx on public.hospital_announcements (hospital_id, published_at desc);
create index audit_logs_hospital_created_idx on public.audit_logs (hospital_id, created_at desc);
create index audit_logs_user_created_idx on public.audit_logs (user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_hospital_classifications_updated_at before update on public.hospital_classifications for each row execute function public.set_updated_at();
create trigger set_hospitals_updated_at before update on public.hospitals for each row execute function public.set_updated_at();
create trigger set_users_updated_at before update on public.users for each row execute function public.set_updated_at();
create trigger set_departments_updated_at before update on public.hospital_departments for each row execute function public.set_updated_at();
create trigger set_services_updated_at before update on public.hospital_services for each row execute function public.set_updated_at();
create trigger set_doctors_updated_at before update on public.doctors for each row execute function public.set_updated_at();
create trigger set_patients_updated_at before update on public.patients for each row execute function public.set_updated_at();
create trigger set_guest_requests_updated_at before update on public.guest_consultation_requests for each row execute function public.set_updated_at();
create trigger set_consultations_updated_at before update on public.consultations for each row execute function public.set_updated_at();
create trigger set_medical_records_updated_at before update on public.medical_records for each row execute function public.set_updated_at();
create trigger set_laboratory_results_updated_at before update on public.laboratory_results for each row execute function public.set_updated_at();
create trigger set_prescriptions_updated_at before update on public.prescriptions for each row execute function public.set_updated_at();
create trigger set_chat_conversations_updated_at before update on public.chat_conversations for each row execute function public.set_updated_at();

create or replace function public.set_guest_reference_number()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.reference_number is null or btrim(new.reference_number) = '' then
    new.reference_number := format(
      'CNPH-GUEST-%s-%s',
      to_char(current_date, 'YYYY'),
      lpad(nextval('public.guest_consultation_reference_seq')::text, 6, '0')
    );
  end if;
  return new;
end;
$$;

create trigger set_guest_reference before insert on public.guest_consultation_requests for each row execute function public.set_guest_reference_number();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  guest_role_id smallint;
begin
  select id into guest_role_id from public.roles where role_name = 'guest';
  insert into public.users (
    id,
    auth_user_id,
    role_id,
    first_name,
    last_name,
    email,
    mobile_number,
    account_status
  ) values (
    new.id,
    new.id,
    guest_role_id,
    coalesce(new.raw_user_meta_data ->> 'first_name', ''),
    coalesce(new.raw_user_meta_data ->> 'last_name', ''),
    new.email,
    new.phone,
    'active'
  ) on conflict (auth_user_id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_auth_user();

create or replace function public.current_user_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select u.id from public.users u where u.auth_user_id = (select auth.uid()) limit 1
$$;

create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select r.role_name
  from public.users u
  join public.roles r on r.id = u.role_id
  where u.auth_user_id = (select auth.uid())
  limit 1
$$;

create or replace function public.current_hospital_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select u.hospital_id from public.users u where u.auth_user_id = (select auth.uid()) limit 1
$$;

create or replace function public.current_doctor_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select d.id
  from public.doctors d
  where d.user_id = public.current_user_id()
  limit 1
$$;

create or replace function public.current_patient_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select p.id
  from public.patients p
  where p.user_id = public.current_user_id()
  limit 1
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(public.current_role() = 'super_admin', false)
$$;

create or replace function public.is_hospital_admin_for(target_hospital_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    public.is_super_admin()
    or (
      public.current_role() = 'hospital_admin'
      and public.current_hospital_id() = target_hospital_id
    ),
    false
  )
$$;

create or replace function public.can_access_patient(target_patient_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    target_patient_id = public.current_patient_id()
    or exists (
      select 1
      from public.doctor_patient_assignments a
      where a.patient_id = target_patient_id
        and a.doctor_id = public.current_doctor_id()
        and a.ended_at is null
    )
    or exists (
      select 1
      from public.consultations c
      where c.patient_id = target_patient_id
        and c.doctor_id = public.current_doctor_id()
        and c.status in ('approved', 'scheduled', 'in_progress', 'completed')
    ),
    false
  )
$$;

create or replace function public.can_access_guest_request(target_request_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    exists (
      select 1 from public.guest_consultation_requests g
      where g.id = target_request_id and g.submitted_by = (select auth.uid())
    )
    or exists (
      select 1 from public.guest_consultation_requests g
      where g.id = target_request_id and g.assigned_doctor_id = public.current_doctor_id()
    )
    or exists (
      select 1 from public.guest_consultation_requests g
      where g.id = target_request_id and public.is_hospital_admin_for(g.preferred_hospital_id)
    ),
    false
  )
$$;

create or replace function public.can_access_conversation(target_conversation_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(exists (
    select 1
    from public.chat_conversations c
    where c.id = target_conversation_id
      and (
        c.doctor_id = public.current_doctor_id()
        or (c.patient_id is not null and c.patient_id = public.current_patient_id())
        or (c.guest_request_id is not null and public.can_access_guest_request(c.guest_request_id))
      )
  ), false)
$$;

create or replace function public.can_view_user(target_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    target_user_id = public.current_user_id()
    or public.is_super_admin()
    or exists (
      select 1 from public.users target
      where target.id = target_user_id
        and public.current_role() = 'hospital_admin'
        and target.hospital_id = public.current_hospital_id()
    )
    or exists (
      select 1
      from public.patients p
      where p.user_id = target_user_id and public.can_access_patient(p.id)
    ),
    false
  )
$$;

create or replace function public.protect_user_privileges()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_role text := public.current_role();
begin
  if (select auth.uid()) is null or actor_role = 'super_admin' then
    return new;
  end if;

  if actor_role = 'hospital_admin' and old.hospital_id = public.current_hospital_id() then
    if new.auth_user_id is distinct from old.auth_user_id
       or new.role_id is distinct from old.role_id
       or new.hospital_id is distinct from old.hospital_id then
      raise exception 'Hospital administrators cannot change identity, role, or hospital assignment directly';
    end if;
    return new;
  end if;

  if old.auth_user_id = (select auth.uid()) then
    if new.auth_user_id is distinct from old.auth_user_id
       or new.role_id is distinct from old.role_id
       or new.hospital_id is distinct from old.hospital_id
       or new.account_status is distinct from old.account_status then
      raise exception 'Role, hospital, identity, and account status are protected';
    end if;
    return new;
  end if;

  raise exception 'Not authorized to update this user';
end;
$$;

create trigger protect_user_privileges_before_update
  before update on public.users
  for each row execute function public.protect_user_privileges();

create or replace function public.nearby_hospitals(
  user_latitude double precision,
  user_longitude double precision,
  radius_km double precision default 100
)
returns table (
  id uuid,
  hospital_name text,
  classification_name text,
  address text,
  latitude numeric,
  longitude numeric,
  contact_number text,
  emergency_contact_number text,
  operating_status public.hospital_operating_status,
  distance_km double precision
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    h.id,
    h.hospital_name,
    hc.classification_name,
    h.address,
    h.latitude,
    h.longitude,
    h.contact_number,
    h.emergency_contact_number,
    h.operating_status,
    6371 * acos(least(1, greatest(-1,
      cos(radians(user_latitude))
      * cos(radians(h.latitude::double precision))
      * cos(radians(h.longitude::double precision) - radians(user_longitude))
      + sin(radians(user_latitude))
      * sin(radians(h.latitude::double precision))
    ))) as distance_km
  from public.hospitals h
  left join public.hospital_classifications hc on hc.id = h.classification_id
  where h.verification_status = 'verified'
    and h.operating_status in ('open', 'limited')
    and h.latitude is not null
    and h.longitude is not null
    and 6371 * acos(least(1, greatest(-1,
      cos(radians(user_latitude))
      * cos(radians(h.latitude::double precision))
      * cos(radians(h.longitude::double precision) - radians(user_longitude))
      + sin(radians(user_latitude))
      * sin(radians(h.latitude::double precision))
    ))) <= radius_km
  order by distance_km;
$$;

alter table public.roles enable row level security;
alter table public.hospital_classifications enable row level security;
alter table public.hospitals enable row level security;
alter table public.users enable row level security;
alter table public.hospital_departments enable row level security;
alter table public.hospital_services enable row level security;
alter table public.hospital_rooms enable row level security;
alter table public.hospital_beds enable row level security;
alter table public.emergency_room_status enable row level security;
alter table public.hospital_facility_status enable row level security;
alter table public.doctors enable row level security;
alter table public.doctor_schedules enable row level security;
alter table public.patients enable row level security;
alter table public.doctor_patient_assignments enable row level security;
alter table public.guest_consultation_requests enable row level security;
alter table public.consultations enable row level security;
alter table public.medical_records enable row level security;
alter table public.laboratory_results enable row level security;
alter table public.prescriptions enable row level security;
alter table public.ai_assessments enable row level security;
alter table public.chat_conversations enable row level security;
alter table public.chat_messages enable row level security;
alter table public.notifications enable row level security;
alter table public.hospital_announcements enable row level security;
alter table public.audit_logs enable row level security;

create policy roles_read on public.roles for select to authenticated using (true);
create policy roles_super_admin_manage on public.roles for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());

create policy classifications_public_read on public.hospital_classifications for select to anon, authenticated using (true);
create policy classifications_super_admin_manage on public.hospital_classifications for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());

create policy hospitals_public_read on public.hospitals for select to anon, authenticated
  using (
    (verification_status = 'verified' and operating_status in ('open', 'limited'))
    or public.is_hospital_admin_for(id)
  );
create policy hospitals_super_admin_insert on public.hospitals for insert to authenticated with check (public.is_super_admin());
create policy hospitals_admin_update on public.hospitals for update to authenticated using (public.is_hospital_admin_for(id)) with check (public.is_hospital_admin_for(id));
create policy hospitals_super_admin_delete on public.hospitals for delete to authenticated using (public.is_super_admin());

create policy users_authorized_read on public.users for select to authenticated using (public.can_view_user(id));
create policy users_authorized_update on public.users for update to authenticated
  using (auth_user_id = (select auth.uid()) or public.is_hospital_admin_for(hospital_id))
  with check (auth_user_id = (select auth.uid()) or public.is_hospital_admin_for(hospital_id));

create policy departments_public_read on public.hospital_departments for select to anon, authenticated
  using (
    (availability_status <> 'unavailable' and exists (
      select 1 from public.hospitals h
      where h.id = hospital_id and h.verification_status = 'verified' and h.operating_status in ('open', 'limited')
    ))
    or public.is_hospital_admin_for(hospital_id)
  );
create policy departments_admin_manage on public.hospital_departments for all to authenticated using (public.is_hospital_admin_for(hospital_id)) with check (public.is_hospital_admin_for(hospital_id));

create policy services_public_read on public.hospital_services for select to anon, authenticated
  using (
    (availability_status <> 'unavailable' and exists (
      select 1 from public.hospitals h
      where h.id = hospital_id and h.verification_status = 'verified' and h.operating_status in ('open', 'limited')
    ))
    or public.is_hospital_admin_for(hospital_id)
  );
create policy services_admin_manage on public.hospital_services for all to authenticated using (public.is_hospital_admin_for(hospital_id)) with check (public.is_hospital_admin_for(hospital_id));

create policy rooms_public_read on public.hospital_rooms for select to anon, authenticated
  using (exists (select 1 from public.hospitals h where h.id = hospital_id and h.verification_status = 'verified') or public.is_hospital_admin_for(hospital_id));
create policy rooms_admin_manage on public.hospital_rooms for all to authenticated using (public.is_hospital_admin_for(hospital_id)) with check (public.is_hospital_admin_for(hospital_id));

create policy beds_public_read on public.hospital_beds for select to anon, authenticated
  using (exists (select 1 from public.hospitals h where h.id = hospital_id and h.verification_status = 'verified') or public.is_hospital_admin_for(hospital_id));
create policy beds_admin_manage on public.hospital_beds for all to authenticated using (public.is_hospital_admin_for(hospital_id)) with check (public.is_hospital_admin_for(hospital_id));

create policy emergency_status_public_read on public.emergency_room_status for select to anon, authenticated
  using (exists (select 1 from public.hospitals h where h.id = hospital_id and h.verification_status = 'verified') or public.is_hospital_admin_for(hospital_id));
create policy emergency_status_admin_manage on public.emergency_room_status for all to authenticated using (public.is_hospital_admin_for(hospital_id)) with check (public.is_hospital_admin_for(hospital_id));

create policy facility_status_public_read on public.hospital_facility_status for select to anon, authenticated
  using (exists (select 1 from public.hospitals h where h.id = hospital_id and h.verification_status = 'verified') or public.is_hospital_admin_for(hospital_id));
create policy facility_status_admin_manage on public.hospital_facility_status for all to authenticated using (public.is_hospital_admin_for(hospital_id)) with check (public.is_hospital_admin_for(hospital_id));

create policy doctors_public_read on public.doctors for select to anon, authenticated
  using (
    (availability_status <> 'unavailable' and exists (
      select 1 from public.hospitals h where h.id = hospital_id and h.verification_status = 'verified'
    ))
    or user_id = public.current_user_id()
    or public.is_hospital_admin_for(hospital_id)
  );
create policy doctors_admin_manage on public.doctors for all to authenticated using (public.is_hospital_admin_for(hospital_id)) with check (public.is_hospital_admin_for(hospital_id));

create policy doctor_schedules_public_read on public.doctor_schedules for select to anon, authenticated using (is_active or doctor_id = public.current_doctor_id());
create policy doctor_schedules_manage on public.doctor_schedules for all to authenticated
  using (
    doctor_id = public.current_doctor_id()
    or exists (select 1 from public.doctors d where d.id = doctor_id and public.is_hospital_admin_for(d.hospital_id))
  )
  with check (
    doctor_id = public.current_doctor_id()
    or exists (select 1 from public.doctors d where d.id = doctor_id and public.is_hospital_admin_for(d.hospital_id))
  );

create policy patients_authorized_read on public.patients for select to authenticated
  using (public.can_access_patient(id) or public.is_hospital_admin_for(primary_hospital_id));
create policy patients_doctor_insert on public.patients for insert to authenticated with check (created_by_doctor = public.current_doctor_id());
create policy patients_doctor_update on public.patients for update to authenticated using (public.can_access_patient(id)) with check (public.can_access_patient(id));

create policy assignments_participant_read on public.doctor_patient_assignments for select to authenticated
  using (doctor_id = public.current_doctor_id() or patient_id = public.current_patient_id() or public.can_access_patient(patient_id));
create policy assignments_doctor_manage on public.doctor_patient_assignments for all to authenticated
  using (
    doctor_id = public.current_doctor_id()
    or exists (select 1 from public.doctors d where d.id = doctor_id and public.is_hospital_admin_for(d.hospital_id))
  )
  with check (
    doctor_id = public.current_doctor_id()
    or exists (select 1 from public.doctors d where d.id = doctor_id and public.is_hospital_admin_for(d.hospital_id))
  );

create policy guest_requests_owner_insert on public.guest_consultation_requests for insert to authenticated with check (submitted_by = (select auth.uid()));
create policy guest_requests_authorized_read on public.guest_consultation_requests for select to authenticated using (public.can_access_guest_request(id));
create policy guest_requests_reviewer_update on public.guest_consultation_requests for update to authenticated
  using (assigned_doctor_id = public.current_doctor_id() or public.is_hospital_admin_for(preferred_hospital_id))
  with check (assigned_doctor_id = public.current_doctor_id() or public.is_hospital_admin_for(preferred_hospital_id));

create policy consultations_participant_read on public.consultations for select to authenticated
  using (
    patient_id = public.current_patient_id()
    or doctor_id = public.current_doctor_id()
    or (guest_request_id is not null and public.can_access_guest_request(guest_request_id))
    or public.is_hospital_admin_for(hospital_id)
  );
create policy consultations_patient_insert on public.consultations for insert to authenticated
  with check (patient_id = public.current_patient_id());
create policy consultations_doctor_update on public.consultations for update to authenticated
  using (doctor_id = public.current_doctor_id() or public.is_hospital_admin_for(hospital_id))
  with check (doctor_id = public.current_doctor_id() or public.is_hospital_admin_for(hospital_id));

create policy medical_records_care_team_read on public.medical_records for select to authenticated using (public.can_access_patient(patient_id));
create policy medical_records_doctor_insert on public.medical_records for insert to authenticated with check (doctor_id = public.current_doctor_id() and public.can_access_patient(patient_id));
create policy medical_records_doctor_update on public.medical_records for update to authenticated using (doctor_id = public.current_doctor_id()) with check (doctor_id = public.current_doctor_id());

create policy laboratory_results_care_team_read on public.laboratory_results for select to authenticated using (public.can_access_patient(patient_id));
create policy laboratory_results_doctor_insert on public.laboratory_results for insert to authenticated with check (doctor_id = public.current_doctor_id() and public.can_access_patient(patient_id));
create policy laboratory_results_doctor_update on public.laboratory_results for update to authenticated using (doctor_id = public.current_doctor_id()) with check (doctor_id = public.current_doctor_id());

create policy prescriptions_care_team_read on public.prescriptions for select to authenticated using (public.can_access_patient(patient_id));
create policy prescriptions_doctor_insert on public.prescriptions for insert to authenticated with check (doctor_id = public.current_doctor_id() and public.can_access_patient(patient_id));
create policy prescriptions_doctor_update on public.prescriptions for update to authenticated using (doctor_id = public.current_doctor_id()) with check (doctor_id = public.current_doctor_id());

create policy ai_assessments_owner_read on public.ai_assessments for select to authenticated
  using (
    user_id = (select auth.uid())
    or (patient_id is not null and public.can_access_patient(patient_id))
    or (guest_request_id is not null and public.can_access_guest_request(guest_request_id))
  );
create policy ai_assessments_owner_insert on public.ai_assessments for insert to authenticated with check (user_id = (select auth.uid()));

create policy conversations_participant_read on public.chat_conversations for select to authenticated using (public.can_access_conversation(id));
create policy conversations_doctor_manage on public.chat_conversations for all to authenticated
  using (doctor_id = public.current_doctor_id())
  with check (doctor_id = public.current_doctor_id());

create policy messages_participant_read on public.chat_messages for select to authenticated using (public.can_access_conversation(conversation_id));
create policy messages_participant_insert on public.chat_messages for insert to authenticated
  with check (sender_id = (select auth.uid()) and public.can_access_conversation(conversation_id));
create policy messages_participant_update on public.chat_messages for update to authenticated using (public.can_access_conversation(conversation_id)) with check (public.can_access_conversation(conversation_id));

create policy notifications_owner_read on public.notifications for select to authenticated using (user_id = (select auth.uid()));
create policy notifications_owner_update on public.notifications for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

create policy announcements_public_read on public.hospital_announcements for select to anon, authenticated
  using (published_at <= now() and (expires_at is null or expires_at > now()));
create policy announcements_admin_manage on public.hospital_announcements for all to authenticated
  using ((is_global and public.is_super_admin()) or (hospital_id is not null and public.is_hospital_admin_for(hospital_id)))
  with check ((is_global and public.is_super_admin()) or (hospital_id is not null and public.is_hospital_admin_for(hospital_id)));

create policy audit_logs_admin_read on public.audit_logs for select to authenticated
  using (public.is_super_admin() or public.is_hospital_admin_for(hospital_id));

revoke all on table public.users, public.patients, public.doctor_patient_assignments,
  public.guest_consultation_requests, public.consultations, public.medical_records,
  public.laboratory_results, public.prescriptions, public.ai_assessments,
  public.chat_conversations, public.chat_messages, public.notifications, public.audit_logs
  from anon;

grant select on public.hospital_classifications, public.hospitals, public.hospital_departments,
  public.hospital_services, public.hospital_rooms, public.hospital_beds,
  public.emergency_room_status, public.hospital_facility_status, public.doctors,
  public.doctor_schedules, public.hospital_announcements to anon, authenticated;
grant select on public.roles to authenticated;
grant select, update on public.users to authenticated;
grant select, insert, update on public.patients, public.doctor_patient_assignments,
  public.guest_consultation_requests, public.consultations, public.medical_records,
  public.laboratory_results, public.prescriptions, public.ai_assessments,
  public.chat_conversations, public.chat_messages, public.notifications to authenticated;
grant select on public.audit_logs to authenticated;
grant insert, update, delete on public.hospital_classifications, public.hospitals,
  public.hospital_departments, public.hospital_services, public.hospital_rooms,
  public.hospital_beds, public.emergency_room_status, public.hospital_facility_status,
  public.doctors, public.doctor_schedules, public.hospital_announcements to authenticated;
grant usage, select on sequence public.guest_consultation_reference_seq to authenticated;

revoke all on function public.handle_new_auth_user() from public, anon, authenticated;
revoke all on function public.protect_user_privileges() from public, anon, authenticated;
revoke all on function public.set_guest_reference_number() from public, anon, authenticated;
grant execute on function public.current_user_id(), public.current_role(), public.current_hospital_id(),
  public.current_doctor_id(), public.current_patient_id(), public.is_super_admin(),
  public.is_hospital_admin_for(uuid), public.can_access_patient(uuid),
  public.can_access_guest_request(uuid), public.can_access_conversation(uuid),
  public.can_view_user(uuid) to authenticated;
grant execute on function public.nearby_hospitals(double precision, double precision, double precision) to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values
  ('profile-images', 'profile-images', false, 5242880, array['image/jpeg', 'image/png', 'image/webp']),
  ('hospital-images', 'hospital-images', true, 10485760, array['image/jpeg', 'image/png', 'image/webp']),
  ('valid-identification', 'valid-identification', false, 10485760, array['image/jpeg', 'image/png', 'application/pdf']),
  ('guest-consultation-documents', 'guest-consultation-documents', false, 20971520, array['image/jpeg', 'image/png', 'application/pdf']),
  ('laboratory-results', 'laboratory-results', false, 20971520, array['image/jpeg', 'image/png', 'application/pdf']),
  ('scanned-medical-results', 'scanned-medical-results', false, 20971520, array['image/jpeg', 'image/png', 'application/pdf']),
  ('medical-documents', 'medical-documents', false, 20971520, array['image/jpeg', 'image/png', 'application/pdf']),
  ('prescriptions', 'prescriptions', false, 10485760, array['image/jpeg', 'image/png', 'application/pdf']),
  ('consultation-attachments', 'consultation-attachments', false, 20971520, array['image/jpeg', 'image/png', 'application/pdf']),
  ('doctor-documents', 'doctor-documents', false, 20971520, array['image/jpeg', 'image/png', 'application/pdf']),
  ('hospital-accreditation-documents', 'hospital-accreditation-documents', false, 20971520, array['image/jpeg', 'image/png', 'application/pdf'])
on conflict (id) do nothing;

create or replace function public.storage_path_owner(object_name text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((storage.foldername(object_name))[1] = (select auth.uid())::text, false)
$$;

create or replace function public.can_access_patient_storage(object_name text)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  folder text := (storage.foldername(object_name))[1];
begin
  if folder is null or folder !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    return false;
  end if;
  return public.can_access_patient(folder::uuid);
end;
$$;

grant execute on function public.storage_path_owner(text), public.can_access_patient_storage(text) to authenticated;

create policy cnph_hospital_images_public_read on storage.objects for select to anon, authenticated using (bucket_id = 'hospital-images');
create policy cnph_hospital_images_admin_insert on storage.objects for insert to authenticated
  with check (bucket_id = 'hospital-images' and public.current_role() in ('hospital_admin', 'super_admin'));
create policy cnph_hospital_images_admin_update on storage.objects for update to authenticated
  using (bucket_id = 'hospital-images' and public.current_role() in ('hospital_admin', 'super_admin'))
  with check (bucket_id = 'hospital-images' and public.current_role() in ('hospital_admin', 'super_admin'));
create policy cnph_hospital_images_admin_delete on storage.objects for delete to authenticated
  using (bucket_id = 'hospital-images' and public.current_role() in ('hospital_admin', 'super_admin'));

create policy cnph_profile_images_owner_read on storage.objects for select to authenticated
  using (bucket_id = 'profile-images' and public.storage_path_owner(name));
create policy cnph_profile_images_owner_insert on storage.objects for insert to authenticated
  with check (bucket_id = 'profile-images' and public.storage_path_owner(name));
create policy cnph_profile_images_owner_update on storage.objects for update to authenticated
  using (bucket_id = 'profile-images' and public.storage_path_owner(name))
  with check (bucket_id = 'profile-images' and public.storage_path_owner(name));
create policy cnph_profile_images_owner_delete on storage.objects for delete to authenticated
  using (bucket_id = 'profile-images' and public.storage_path_owner(name));

create policy cnph_guest_documents_owner_read on storage.objects for select to authenticated
  using (bucket_id in ('valid-identification', 'guest-consultation-documents') and public.storage_path_owner(name));
create policy cnph_guest_documents_owner_insert on storage.objects for insert to authenticated
  with check (bucket_id in ('valid-identification', 'guest-consultation-documents') and public.storage_path_owner(name));
create policy cnph_guest_documents_owner_delete on storage.objects for delete to authenticated
  using (bucket_id in ('valid-identification', 'guest-consultation-documents') and public.storage_path_owner(name));

create policy cnph_patient_documents_care_team_read on storage.objects for select to authenticated
  using (
    bucket_id in ('laboratory-results', 'scanned-medical-results', 'medical-documents', 'prescriptions', 'consultation-attachments')
    and public.can_access_patient_storage(name)
  );
create policy cnph_patient_documents_doctor_insert on storage.objects for insert to authenticated
  with check (
    bucket_id in ('laboratory-results', 'scanned-medical-results', 'medical-documents', 'prescriptions', 'consultation-attachments')
    and public.current_role() = 'doctor'
    and public.can_access_patient_storage(name)
  );

create policy cnph_admin_documents_read on storage.objects for select to authenticated
  using (bucket_id in ('doctor-documents', 'hospital-accreditation-documents') and public.current_role() in ('hospital_admin', 'super_admin'));
create policy cnph_admin_documents_insert on storage.objects for insert to authenticated
  with check (bucket_id in ('doctor-documents', 'hospital-accreditation-documents') and public.current_role() in ('hospital_admin', 'super_admin'));

do $$
declare
  realtime_table text;
begin
  foreach realtime_table in array array[
    'emergency_room_status',
    'hospital_rooms',
    'hospital_beds',
    'doctor_schedules',
    'consultations',
    'chat_messages',
    'notifications'
  ]
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = realtime_table
    ) then
      execute format('alter publication supabase_realtime add table public.%I', realtime_table);
    end if;
  end loop;
end;
$$;

commit;
